DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS cohorts;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    age INTEGER NOT NULL,
    person  TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    country TEXT NOT NULL,
    cohort TEXT NOT NULL,
    addr TEXT NOT NULL
);

CREATE TABLE cohorts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    leader TEXT NOT NULL,
    descrip TEXT NOT NULL,
    place TEXT NOT NULL
);