jobdata ={
    "Agriculture": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet1",
    "Construction": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet12",
    "Culture Sports and Entertainment": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet13",
    "Education": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet14",
    "Employed": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet15",
    "Financial Intermediation": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet16",
    "Health and Social Service": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet17",
    "Hotels and Catering Services": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet18",
    "Information Transmission, Software and Information Technology": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet19",
    "Leasing and Business Services": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet110",
    "Management of Water Conservancy Environment and Public Facilities": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet111",
    "Manufacturing":"https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet12",
    "Mining":"https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet113",
    "Production and Supply of Electricity Heat Gas and Water":"https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet114",
    "Public Management. Social Security and Social Organization":"https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet115",
    "Real Estate":"https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet116",
    "Scientific Research and Technical Services": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet117",
    "Services to Households, Repair and Other Services": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet118",
    "Transport, Storage, and Post": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet119",
    "Wholesale and Retail Trades": "https://10az.online.tableau.com/t/rosehack/views/Book4_1/Sheet120",
}