{'Anhui': '',
 'Beijing': 'https://10az.online.tableau.com/t/rosehack/views/Book2/Sheet1',
 'Chongqing': '',
 'Fujian': '',
 'Gansu': '',
 'Guangxe': 'https://10az.online.tableau.com/#/site/rosehack/views/Book3/Sheet1', # double chekc this one
 'Guizhou': '',
 'Hainan': '',
 'Hebei': '',
 'Heilongjiang': '',
 'Henan': '',
 'Hong Kong': '',
 'Hubei': '',
 'Hunan': '',
 'Inner Mongolia': '',
 'Jiangsu': '',
 'Jiangxi': '',
 'Jilin': '',
 'Liaoning': '',
 'Ningxia': '',
 'Qinghai': '',
 'Shaanxi': '',
 'Shandong': '',
 'Shanghai': '',
 'Shanxi': 'https://10az.online.tableau.com/t/rosehack/views/Shanxi/Sheet1',
 'Sichuan': 'https://10az.online.tableau.com/#/site/rosehack/views/Sichuan/Sheet1',
 'Taiwan': '',
 'Tianjin': '',
 'Xinjiang': '',
 'Xizang (Tibet)': '',
 'Yunnan': '',
 'Zhejiang': ''}